/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/earth2.glb --transform 
Files: public/earth2.glb [135.31KB] > C:\Users\Bonus\mybonuspro\mywebsite\earth2\earth2-transformed.glb [42.44KB] (69%)
*/

import React from 'react'
import { useGLTF,Text,Line,Billboard } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/earth2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.001']} scale={5} />
      <mesh geometry={nodes.Sphere001.geometry} material={materials['Material.002']} scale={4.784} />
      <mesh geometry={nodes.Sphere002.geometry} material={materials['Material.003']} scale={4.484} />
      <mesh geometry={nodes.Sphere003.geometry} material={materials['Material.004']} scale={3.331} />
      <mesh geometry={nodes.Sphere004.geometry} material={materials['Material.005']} scale={2.642} />

      <group>
        <Line points={[[0,5,0],[0,6,-5]]} color="black" lineWidth={2} />
        <Billboard position={[0,6,-6]}>
          <Text fontSize={0.5} color="black" anchorX="center" anchorY="middle">
            ธรณีภาค
          </Text>
        </Billboard>
      </group>

        <group>
        <Line points={[[0,4.7,-0.5],[0,4.5,-5]]} color="black" lineWidth={2} />
        <Billboard position={[0,4.5,-6.5]}>
          <Text fontSize={0.5} color="black" anchorX="center" anchorY="middle">
            ฐานธรณีภาค
          </Text>
        </Billboard>
      </group>

      <group>
        <Line points={[[0,3.5,-0.5],[0,3.5,-5.3]]} color="black" lineWidth={2} />
        <Billboard position={[0,3.5,-6.5]}>
          <Text fontSize={0.5} color="black" anchorX="center" anchorY="middle">
            มัชฌิมภาค
          </Text>
        </Billboard>
      </group>

      <group>
        <Line points={[[0,2,-0.5],[0,2.5,-4.8]]} color="black" lineWidth={2} />
        <Billboard position={[0,2.5,-6.5]}>
          <Text fontSize={0.5} color="black" anchorX="center" anchorY="middle">
            แก่นโลกชั้นนอก
          </Text>
        </Billboard>
      </group>

      <group>
        <Line points={[[0,0,-0.5],[0,0,-4.8]]} color="black" lineWidth={2} />
        <Billboard position={[0,0,-6.2]}>
          <Text fontSize={0.5} color="black" anchorX="center" anchorY="middle">
            แก่นโลกชั้นใน
          </Text>
        </Billboard>
      </group>
    </group>
  )
}

useGLTF.preload('/earth2-transformed.glb')
